import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import TopNav from "~/components/TopNav";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { Toaster } from "~/components/ui/sonner";
import { PostHogProvider } from "./_analytics/providers";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
  modal,
}: Readonly<{ children: React.ReactNode;
  modal: React.ReactNode;
 }>) {
  return (
    <ClerkProvider>
      <PostHogProvider>
    <html lang="en" className={`${GeistSans.variable} dark`}>
    <NextSSRPlugin
          /**
           * The `extractRouterConfig` will extract **only** the route configs
           * from the router to prevent additional information from being
           * leaked to the client. The data passed to the client is the same
           * as if you were to fetch `/api/uploadthing` directly.
           */
          routerConfig={extractRouterConfig(ourFileRouter)}
        />
      <body className="dark">
        <div className="h-screen grid grid-flow-rows-[auto, 1fr, 1fr, 2fr]">
          <TopNav />
          <main className="overflow-y-scroll">
            {children}
          </main>
          
        </div>
        {modal}
        <Toaster />
      </body>
    </html>
    </PostHogProvider>
    </ClerkProvider>
  );
}
